# Generated by Django 4.2.5 on 2023-09-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('deviceModel', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('serial', models.CharField(max_length=20)),
            ],
        ),
    ]
